apiVersion: apps/v1
kind: Deployment
metadata:
  name: restmail-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restmail-receiver
  template:
    metadata:
      labels:
        app: restmail-receiver
    spec:
      containers:
      - name: receiver
        image: restmail-receiver:latest
        imagePullPolicy: Never # Viktig når vi bruker lokalt register
        env:
        - name: RESTMAIL_POLICY_PORT
          value: "12345"
        - name: RESTMAIL_DELIVERY_PORT
          value: "2525"
        - name: RESTMAIL_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: RESTMAIL_STORAGE_BASE_PATH
          value: "/var/mail/restmail"
        - name: RESTMAIL_STORAGE_INCOMING
          value: "incoming"
        ports:
        - containerPort: 2525
          name: delivery
        - containerPort: 12345
          name: policy
        volumeMounts:
        - name: mail-storage
          mountPath: /var/mail/restmail
      volumes:
      - name: mail-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: restmail-service
spec:
  type: NodePort
  selector:
    app: restmail-receiver
  ports:
    - name: delivery
      protocol: TCP
      port: 2525
      targetPort: 2525
      nodePort: 30025 # Denne må matche Postfix transport-filen
    - name: policy
      protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 30345
